import { test, expect } from '@playwright/test'

const ledger = '.channel-flat-ledger'
const rows = `${ledger} tbody tr`
async function open(page) {
  const requests = []
  await page.route(url => url.pathname.startsWith('/api/'), route => {
    requests.push(route.request().method() + ' ' + new URL(route.request().url()).pathname)
    if (new URL(route.request().url()).pathname === '/api/bill-lifecycle/archive') {
      return route.fulfill({ json: { archived_ids: ['archived'], eligible_ids: [], items: [] } })
    }
    if (new URL(route.request().url()).pathname === '/api/auth/me') {
      return route.fulfill({ json: { role: 'admin', permissions: [] } })
    }
    return route.abort()
  })
  page.on('pageerror', error => { throw error })
  await page.goto('/tests/fixtures/channel-detail.html')
  await expect(page.locator(rows)).toHaveCount(28)
  return requests
}

test('one shared channel dropdown clears selection and resets pagination', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  const requests = await open(page)
  const select = page.getByLabel('筛选明细渠道')
  await expect(select.locator('option')).toHaveText(['全部渠道', '八门', '百分', '归档渠道'])
  await page.getByLabel('每页账单数量').selectOption('25')
  await page.getByRole('button', { name: '下一页', exact: true }).click()
  await page.getByLabel('选择当前页全部可操作账单').check()
  await select.selectOption('百分')
  await expect(page.getByLabel('筛选明细渠道')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '清除渠道筛选' })).toContainText('百分')
  await expect(page.locator(rows)).toHaveCount(14)
  await expect(page.locator(`${ledger} tbody input:checked`)).toHaveCount(0)
  await expect(page.locator(`${ledger} footer strong`)).toHaveText('1 / 1')
  await expect(page.locator(`${ledger} tbody`)).not.toContainText('八门')
  await select.selectOption('')
  await expect(page.getByRole('button', { name: '清除渠道筛选' })).toHaveCount(0)
  await expect(page.locator(`${ledger} footer strong`)).toHaveText('1 / 2')

  await page.getByLabel('搜索渠道账单').fill('八')
  await expect(select).toHaveValue('')
  await expect(page.locator(rows)).toHaveCount(14)
  await select.selectOption('百分')
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await expect(select).toHaveValue('')
  await expect(page.getByRole('button', { name: '清除渠道筛选' })).toHaveCount(0)
  expect(requests.sort()).toEqual(['GET /api/auth/me', 'GET /api/bill-lifecycle/archive'])
})

test('channel selection combines with game/month filters and keeps archive choices available', async ({ page }) => {
  await open(page)
  const select = page.getByLabel('筛选明细渠道')
  await select.selectOption('百分')
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await page.getByLabel('游戏名称', { exact: true }).fill('游戏甲')
  await page.getByLabel('起始月份', { exact: true }).fill('2026-09')
  await page.getByLabel('结束月份', { exact: true }).fill('2026-09')
  await expect(page.locator(rows)).toHaveCount(3)
  await expect(page.locator(`${ledger} tbody`)).not.toContainText('游戏乙')
  await expect(page.locator(`${ledger} tbody`)).not.toContainText('2026-08')
  await expect(select.locator('option')).toHaveCount(4)
  await page.getByRole('tab', { name: '按渠道汇总', exact: true }).click()
  await expect(page.locator('.channel-group-panel-title')).toContainText('1 个渠道 · 3 张账单')
  await page.getByRole('tab', { name: '账单明细', exact: true }).click()
  await expect(select).toHaveValue('百分')
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await select.selectOption('归档渠道')
  await expect(page.locator('.channel-flat-ledger__empty')).toBeVisible()
  await page.getByRole('button', { name: /归档账单/ }).click()
  await expect(page.locator(rows)).toHaveCount(1)
  await expect(page.locator(`${ledger} tbody`)).toContainText('归档渠道')
})

test('compact filters occupy one desktop row and remain usable on phones', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await open(page)
  await expect(page.locator('.channel-ledger-extra-filters')).toHaveCount(0)
  await expect(page.getByLabel('搜索渠道', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('游戏名称', { exact: true })).toHaveCount(0)
  const boxes = await page.locator('.channel-ledger-filters__main > *').evaluateAll(elements =>
    elements.map(element => ({ bottom: element.getBoundingClientRect().bottom })))
  expect(boxes).toHaveLength(5)
  expect(new Set(boxes.map(box => box.bottom)).size).toBe(1)
  await page.screenshot({ path: testInfo.outputPath('filters-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  const bounds = await page.locator('.channel-ledger-filters :is(input, select, button)').evaluateAll(elements =>
    elements.map(element => ({ x: element.getBoundingClientRect().x, right: element.getBoundingClientRect().right })))
  for (const bound of bounds) {
    expect(bound.x).toBeGreaterThanOrEqual(0)
    expect(bound.right).toBeLessThanOrEqual(390)
  }
  await page.screenshot({ path: testInfo.outputPath('filters-mobile.png') })
  await page.getByLabel('筛选明细渠道').selectOption('八门')
  await expect(page.locator(rows)).toHaveCount(14)
})

test('collapsed advanced filters remain visible as removable conditions; month and range are exclusive', async ({ page }) => {
  await open(page)
  await page.getByLabel('筛选明细渠道').selectOption('百分')
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await page.getByLabel('游戏名称', { exact: true }).fill('游戏甲')
  await page.getByLabel('起始月份', { exact: true }).fill('2026-09')
  await page.getByLabel('结束月份', { exact: true }).fill('2026-09')
  await page.getByLabel('排序方式', { exact: true }).selectOption('month-asc')
  await expect(page.locator(rows)).toHaveCount(3)
  await page.getByRole('button', { name: /收起筛选/ }).click()
  await expect(page.getByRole('button', { name: '更多筛选（3）', exact: true })).toBeVisible()
  await expect(page.getByLabel('已选筛选条件')).toContainText('2026-09 至 2026-09')
  await page.getByRole('button', { name: '清除游戏筛选', exact: true }).click()
  await expect(page.locator(rows)).toHaveCount(7)
  await page.getByLabel('筛选明细结算月份').selectOption('2026-08')
  await expect(page.getByRole('button', { name: '清除日期范围筛选' })).toHaveCount(0)
  await expect(page.locator(rows)).toHaveCount(7)
  await page.getByRole('button', { name: /更多筛选/ }).click()
  await expect(page.getByLabel('起始月份', { exact: true })).toHaveValue('')
  await page.getByLabel('起始月份', { exact: true }).fill('2026-09')
  await expect(page.getByLabel('筛选明细结算月份')).toHaveValue('')
  await page.getByLabel('结束月份', { exact: true }).fill('2026-08')
  await expect(page.getByText('起始月份不能晚于结束月份')).toBeVisible()
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await expect(page.getByLabel('已选筛选条件')).toHaveCount(0)
  await expect(page.getByLabel('起始月份', { exact: true })).toHaveCount(0)
  await expect(page.locator(rows)).toHaveCount(28)
})

test('status filtering and audit month navigation still use the shared controls', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await page.getByLabel('筛选渠道账单状态').selectOption('cancelled')
  await expect(page.locator('.channel-flat-ledger__empty')).toBeVisible()
  await page.getByRole('button', { name: '清除账单状态筛选' }).click()
  await expect(page.locator(rows)).toHaveCount(28)
  await page.getByLabel('筛选明细渠道').selectOption('百分')
  await page.getByRole('tab', { name: '账期巡检', exact: true }).click()
  await page.getByLabel('截至哪个已结束账期').fill('2026-09')
  await expect(page.locator('.channel-month-audit__matrix tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: '查看百分2026年9月已录账单', exact: true }).click()
  await expect(page.getByRole('tab', { name: '账单明细', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('筛选明细渠道')).toHaveValue('百分')
  await expect(page.getByLabel('筛选明细结算月份')).toHaveValue('2026-09')
  await expect(page.locator(rows)).toHaveCount(7)
})
