import { describe, expect, it } from 'vitest'
import { csvCell, csvRow } from './csvSafety.js'
import { buildInvoiceCsvContent } from './exportAdapters.js'

describe('safe financial CSV export', () => {
  it('doubles embedded quotes and quotes commas/newlines', () => {
    expect(csvCell('合同"A",\n附件')).toBe('"合同""A"",\n附件"')
  })

  it('prevents spreadsheet formula execution in imported business text', () => {
    expect(csvCell('=HYPERLINK("https://evil.example")')).toBe(
      '"\'=HYPERLINK(""https://evil.example"")"'
    )
    expect(csvCell(' \t@SUM(1+1)')).toBe('"\' \t@SUM(1+1)"')
    expect(csvCell('-SUM(1+1)')).toBe('"\'-SUM(1+1)"')
  })

  it('preserves ordinary signed amounts as numeric strings', () => {
    expect(csvCell(-100.5)).toBe('"-100.5"')
    expect(csvCell('12.00')).toBe('"12.00"')
    expect(csvRow(['2026-08', -22.5])).toBe('"2026-08","-22.5"')
  })

  it('protects invoice CSV generated by shared export adapter', () => {
    const text = buildInvoiceCsvContent([{
      title: '=1+1',
      taxNo: '9144"00',
      amount: 300,
      status: '已开',
      issueDate: '2026-10-09',
      remark: '开票说明,\n第二行'
    }])
    expect(text).toContain('"\'=1+1"')
    expect(text).toContain('"9144""00"')
    expect(text).toContain('"开票说明,\n第二行"')
  })
})
